#  https://medium.com/epfl-extension-school/selecting-data-from-a-pandas-dataframe-53917dc39953
#  https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.factorize.html
#  https://www.programcreek.com/python/example/101364/pandas.factorize
#  https://datascience.stackexchange.com/questions/44387/reg-pandas-factorize
#  http://benalexkeen.com/mapping-categorical-data-in-pandas/
#  https://pbpython.com/categorical-encoding.html
#  https://www.geeksforgeeks.org/python-pandas-factorize/
#  https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python#question10
#  https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python
#  https://www.tutorialspoint.com/python_pandas/python_pandas_categorical_data.htm
#  https://pbpython.com/pandas_dtypes_cat.html
#  https://chrisalbon.com/python/data_wrangling/pandas_convert_categorical_to_dummies/
#  https://towardsdatascience.com/the-dummys-guide-to-creating-dummy-variables-f21faddb1d40
#  https://www.dezyre.com/data-science-in-python-tutorial/pandas-introductory-tutorial-part-3
#  https://www.geeksforgeeks.org/python-pandas-dataframe-set_index/
#  https://brohrer.github.io/dataframe_indexing.html
#  https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html
#  http://fastml.com/converting-categorical-data-into-numbers-with-pandas-and-scikit-learn/
#  https://www.guru99.com/numpy-indexing-slicing.html
#  https://www.datacamp.com/community/tutorials/python-numpy-tutorial
#  https://www.datacamp.com/community
#  https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm
#  https://realpython.com/courses/python-git-github-intro/
